# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30e2414b74fd17236e5bd257664141a684bab5fb576cc4307abdfdbffc7fa81885ba7b25b1684bc11d26a1b10465aaeb7273be86ed221281c5fa5adb4eae580a

test:
  secret_key_base: 1f9eb885fd87527fb067e796f3a69d10d43bf77b9b35e7261de584c86e3536ca778125504937a0bda27997863250616cf899107b674e3ab5930b6a0e233d7d40

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
